/**
 * OpenWord website Worker.
 *
 * Serves the built shell from Workers static assets and the Writer WebAssembly
 * runtime from R2, on a single origin. Two constraints force this shape:
 *
 * 1. Workers static assets cap a single file at 25 MiB. `soffice.wasm` and
 *    `soffice.data` are far larger, so they cannot be deployed as assets. R2
 *    has no such cap and bills no egress, which matters when every cold visit
 *    pulls the whole runtime.
 * 2. `runtimeAssetUrl()` in src/writer/runtimeHost.ts rejects any runtime base
 *    URL carrying a scheme or protocol-relative prefix, and threaded LOWA needs
 *    cross-origin isolation. So the runtime has to be same-origin: this Worker
 *    proxies R2 rather than the page fetching a public R2 domain directly.
 *
 * `_headers` covers the static assets but is never applied to responses
 * generated by Worker code, so every response built here sets the isolation
 * headers itself.
 */

const ISOLATION_HEADERS: Record<string, string> = {
  "Cross-Origin-Opener-Policy": "same-origin",
  "Cross-Origin-Embedder-Policy": "require-corp",
  "Cross-Origin-Resource-Policy": "same-origin",
  "X-Content-Type-Options": "nosniff",
};

/* Located anywhere in the path so subpath deployments work unchanged. */
const RUNTIME_MARKER = "/writer-runtime/";

/* Runtime keys are flat file names; forbidding "/" also forbids traversal. */
const RUNTIME_KEY = /^[A-Za-z0-9][A-Za-z0-9._-]*$/;

const CONTENT_TYPES: Record<string, string> = {
  js: "text/javascript; charset=utf-8",
  json: "application/json; charset=utf-8",
  wasm: "application/wasm",
  metadata: "application/json; charset=utf-8",
};

/*
 * Deliberately NOT `immutable`. Runtime file names are stable across engine
 * builds, so a year-long immutable entry would pin a browser to bytes that no
 * longer match runtime-manifest.json after an upgrade, and the runtime host
 * refuses to start on a hash mismatch. Revalidation is cheap (a 304 against the
 * R2 ETag) and the service worker's Cache API copy means repeat visits never
 * reach the network at all.
 */
const RUNTIME_CACHE_CONTROL = "public, max-age=0, must-revalidate";

interface Env {
  ASSETS: Fetcher;
  WRITER_RUNTIME: R2Bucket;
}

function contentTypeFor(key: string): string {
  const extension = key.slice(key.lastIndexOf(".") + 1).toLowerCase();
  return CONTENT_TYPES[extension] ?? "application/octet-stream";
}

function runtimeHeaders(key: string, object: R2Object): Headers {
  const headers = new Headers(ISOLATION_HEADERS);
  object.writeHttpMetadata(headers);
  headers.set("content-type", contentTypeFor(key));
  headers.set("cache-control", RUNTIME_CACHE_CONTROL);
  headers.set("etag", object.httpEtag);
  headers.set("accept-ranges", "bytes");
  return headers;
}

function errorResponse(status: number, message: string, extra?: Record<string, string>): Response {
  const headers = new Headers({ ...ISOLATION_HEADERS, ...extra });
  headers.set("content-type", "text/plain; charset=utf-8");
  return new Response(`${message}\n`, { status, headers });
}

/** Resolves the byte window R2 actually returned, for the Content-Range header. */
function resolveRange(range: R2Range, size: number): { start: number; end: number } {
  if ("suffix" in range) {
    return { start: Math.max(0, size - range.suffix), end: size - 1 };
  }
  const start = range.offset ?? 0;
  const end = range.length === undefined ? size - 1 : Math.min(size, start + range.length) - 1;
  return { start, end };
}

async function serveRuntimeHead(env: Env, key: string): Promise<Response> {
  const object = await env.WRITER_RUNTIME.head(key);
  if (object === null) return errorResponse(404, "Writer runtime asset not found");

  const headers = runtimeHeaders(key, object);
  headers.set("content-length", String(object.size));
  return new Response(null, { status: 200, headers });
}

async function unsatisfiableRange(env: Env, key: string): Promise<Response> {
  const object = await env.WRITER_RUNTIME.head(key);
  const headers = new Headers(ISOLATION_HEADERS);
  headers.set("content-type", "text/plain; charset=utf-8");
  if (object !== null) headers.set("content-range", `bytes */${object.size}`);
  return new Response("Range not satisfiable\n", { status: 416, headers });
}

async function serveRuntimeGet(request: Request, env: Env, key: string): Promise<Response> {
  const hasRange = request.headers.has("range");
  let object: R2ObjectBody | R2Object | null;
  try {
    object = await env.WRITER_RUNTIME.get(key, {
      range: hasRange ? request.headers : undefined,
      onlyIf: request.headers,
    });
  } catch (error) {
    /* R2 rejects a range it cannot satisfy; answer 416 rather than a bare 500. */
    if (hasRange) return await unsatisfiableRange(env, key);
    throw error;
  }

  if (object === null) return errorResponse(404, "Writer runtime asset not found");

  const headers = runtimeHeaders(key, object);

  /* A precondition failed: R2 returns metadata without a body. */
  if (!("body" in object)) return new Response(null, { status: 304, headers });

  /* Content-Length is left to the runtime, which derives it from the R2 body.
     Setting it by hand would contradict any downstream compression of the
     runtime's JavaScript files. HEAD sets it explicitly because it has no
     body to derive it from. */
  if (object.range !== undefined && hasRange) {
    const { start, end } = resolveRange(object.range, object.size);
    headers.set("content-range", `bytes ${start}-${end}/${object.size}`);
    return new Response(object.body, { status: 206, headers });
  }

  return new Response(object.body, { status: 200, headers });
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);
    const marker = url.pathname.indexOf(RUNTIME_MARKER);

    /* Everything that is not a runtime asset is shell. The asset layer applies
       _headers and its own not-found handling. */
    if (marker === -1) return env.ASSETS.fetch(request);

    if (request.method !== "GET" && request.method !== "HEAD") {
      return errorResponse(405, "Method not allowed", { allow: "GET, HEAD" });
    }

    const key = url.pathname.slice(marker + RUNTIME_MARKER.length);
    if (!RUNTIME_KEY.test(key)) return errorResponse(404, "Writer runtime asset not found");

    return request.method === "HEAD"
      ? await serveRuntimeHead(env, key)
      : await serveRuntimeGet(request, env, key);
  },
} satisfies ExportedHandler<Env>;
